image: qq3q/deploy:ubuntu24_php8_3_node20

definitions:
  caches:
    php:
      key:
        files:
          - rest/composer.lock
      path: rest/vendor
  steps:
    - step: &rest_build
        name: Rest Build
        script:
          - cd rest
          - composer install
          - rm -f .env.local
          - touch .env.local
          - echo "DATABASE_URL=$DATABASE_URL" >> .env.local
        caches:
          - composer
          - php
        artifacts:
          - rest/vendor/**
          - rest/.env.local
    - step: &rest_deploy
        name: Rest Deploy
        script:
          - rm -rf rest/.idea rest/var
          - cd rest
          - tar -czf /tmp/rest.tar.gz .
          - scp /tmp/rest.tar.gz $USER@$SERVER:/tmp/
          - ssh $USER@$SERVER "mkdir -p /app/floh2-rest"
          - ssh $USER@$SERVER "rm -rf /app/floh2-rest/tmp/ && mkdir /app/floh2-rest/tmp && cd /app/floh2-rest/tmp && tar -xzf /tmp/app.tar.gz && rm /tmp/app.tar.gz"
          - ssh $USER@$SERVER chown -R www-data:www-data /app/floh2-rest/tmp
          - ssh $USER@$SERVER "rm -rf /app/floh2-rest/last && mv /app/floh2-rest/current /app/floh2-rest/last && mv /app/floh2-rest/tmp /app/floh2-rest/current"
    - step: &rest_migrate
        name: Rest Migrate DB
        script:
          - ssh $USER@$SERVER "sudo -u www-data /app/floh2-rest/current/bin/console doctrine:migrations:migrate --no-interaction --all-or-nothing"

pipelines:
  custom:
    rest:
      - stage:
          name: Deploy rest
          deployment: Production
          steps:
            - step: *rest_build
            - step: *rest_deploy
            - step: *rest_migrate
